let lessons=[
    {
    id:1001,
    subject:"Art",
    location: "Mirdiff",
    price: 1000,
    spaces: 5,
    image: "images/art.png",
},
{
    id:1002,
    subject:"Singing",
    location: "Deira",
    price: 1200,
    spaces: 5,
    image: "images/singing.jpg",
},
{
    id:1003,
    subject:"Gymnastics",
    location: "Jabel Ali",
    price: 2000,
    spaces: 5,
    image: "images/gym.jpg",
},
{
    id:1004,
    subject:"Dancing",
    location: "Palm Jumeirah",
    price: 800,
    spaces: 5,
    image: "images/dancing.jpg",
},
{
    id:1005,
    subject:"Chess",
    location: "Al Safouh",
    price: 500,
    spaces: 5,
    image: "images/chess.png",
},
{
    id:1006,
    subject:"Robotics",
    location: "Downtown Dubai",
    price: 2500,
    spaces: 5,
    image: "images/robotics.jpg",
},
{
    id:1007,
    subject:"Debate",
    location: "Al Barsha",
    price: 600,
    spaces: 5,
    image: "images/debate.jpg",
},
{
    id:1008,
    subject:"Yoga",
    location: "Al Corniche",
    price: 1700,
    spaces: 5,
    image: "images/yoga.jpg",
},
{
    id:1009,
    subject:"Swimming",
    location: "Al Garhoud",
    price: 900,
    spaces: 5,
    image: "images/swimming.jpg",
},
{
    id:1010,
    subject:"Martial Arts",
    location: "Al Mamzar",
    price: 1300,
    spaces: 5,
    image: "images/martialarts.jpg",
},


]

